library(forecast)
 library(readxl)
 library(readxl)
 IPCA.df<-read_excel("c:/Econometria/IPCA.xls")
 plot(IPCA.df$IPCA, type = "l")
 MM<-data.frame(na.omit(ma(IPCA.df$IPCA,order = 12, centre = T)))
 a<-(127-nrow(MM))+1
 IPCA.df<-as.data.frame(IPCA.df$IPCA[a:127])
 Tabelal<-cbind(IPCA.df ,MM)
colnames(Tabelal) <- c ("IPCA","Média Móvel")
View(Tabelal)
 Grafico <- ts(Tabelal, start = 2008, frequency = 12)
plot(Grafico,plot.type = "single", col=c("Black","Blue"))
inflacao <- ts(IPCA.df$IPCA, start = 2008, frequency = 12)
 plot(decompose(inflacao))